name: "Setup Python environment"

inputs:
  python-version:
    required: true

runs:
  using: "composite"
  steps:
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548  # v6.1.0
    with:
      python-version: ${{ inputs.python-version }}
  - name: Install dependencies
    shell: bash
    run: |
      python -m pip install --upgrade pip
      pip install -e '.[dev]'
